name: genLinks

on:
  workflow_dispatch:

jobs:
  genLinks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#    - name: Installation depends
#      run: |
#        sudo apt-get update
#        sudo apt-get upgrade
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install tinify
    - name: start genLinks
      run: |
        cd /home/runner/work/picdev/picdev
        python genLinkFiles.py
#    - name: Delect Rawfile
#      run: |
#        cd /home/runner/work/picdev/picdev
#        rm -f imgs/ani/*
    - name: Push to Repo
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: genLinks
